### ISSUE TITLE
tantar: AccessControlException from AdStorageAdapter causes inscrutable failure

### ISSUE THREAD

**Issue by pdowler** [opencadc/storage-inventory#252]
The response from /ad should be HTTP 403 that HttpTransfer turns into an AccessControlException with the VOTable as the body. It should not be a TransientException because it is not a transient failure - retry will not help.
So, error handling flow in AdStorageAdapter and/or TapClient (cadc-tap) and tantar is not dealing with this well.

```
2021-01-27 20:34:38.647 [main] FATAL Main - 
java.security.PrivilegedActionException: TransientException[<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE xmlns="http://www.ivoa.net/xml/VOTable/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.4">
 <RESOURCE type="results">
  <INFO name="QUERY_STATUS" value="ERROR">permission denied</INFO>
 </RESOURCE>
</VOTABLE>
,30]
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.opencadc.tantar.BucketValidator$1.<init>(BucketValidator.java:608)
	at org.opencadc.tantar.BucketValidator.iterateStorage(BucketValidator.java:603)
	at org.opencadc.tantar.BucketValidator.validate(BucketValidator.java:278)
	at org.opencadc.tantar.Main.main(Main.java:139)
Caused by: TransientException[<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE xmlns="http://www.ivoa.net/xml/VOTable/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.4">
 <RESOURCE type="results">
  <INFO name="QUERY_STATUS" value="ERROR">permission denied</INFO>
 </RESOURCE>
</VOTABLE>
,30]
	at org.opencadc.inventory.storage.ad.AdStorageAdapter.iterator(AdStorageAdapter.java:293)
...```

**Comment by pdowler** [comment]
obsolete
