### ISSUE TITLE
Artifact Iteration crashes with very large dataset

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#95]
Asking the ArtifactDAO to iterate over millions of rows results in an `OutOfMemoryException` as the results are actually gathered.

We may need a paginated solution.  Here is the output from the Tantar project using the `SQLGenerator` class:
```bash
1456 [main] DEBUG SQLGenerator  - ArtifactGet: SELECT uri,uriBucket,contentChecksum,contentLastModified,contentLength,contentType,contentEncoding,siteLocations,storageLocation_storageID,storageLocation_storageBucket,lastModified,metaChecksum,id FROM inventory.Artifact WHERE storageLocation_storageBucket LIKE ? AND storageLocation_storageID IS NOT NULL ORDER BY storageLocation_storageBucket, storageLocation_storageID
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Heap dump file created [1885647612 bytes in 10.179 secs]
445103 [main] DEBUG ArtifactDAO  - iterator: HST 443647ms
END
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.toCharArray(String.java:2899)
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:78)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1054)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2212)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at org.opencadc.inventory.db.SQLGenerator$ArtifactIterator.query(SQLGenerator.java:488)
	at org.opencadc.inventory.db.ArtifactDAO.iterator(ArtifactDAO.java:142)
	at org.opencadc.tantar.BucketValidator.iterateInventory(BucketValidator.java:494)
	at org.opencadc.tantar.BucketValidator.validate(BucketValidator.java:187)
	at org.opencadc.tantar.Main.main(Main.java:108)
```

**Comment by pdowler** [comment]
I think I know how to fix this... needed something like this in tap libs. Will fix.
